services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: cantera_leads
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - cantera_leads_pgdata:/var/lib/postgresql/data

volumes:
  cantera_leads_pgdata:
